name: 'Build & Publish to PyPI'
author: 'Conchylicultor'
description: 'Build and publish to PyPI for PEP 518 compliant projects.'
branding:
  icon: upload-cloud
  color: orange

inputs:
  pypi-token:
    description: 'Token of the PyPI account publishing the project.'
    required: true

runs:
  using: "composite"
  steps:
    - run: pip install build twine
    - run: python -m build
    - run: twine check dist/*
    - run: twine upload dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ inputs.pypi-token }}
